#!/usr/bin/perl

open(LOGFILE, ">TeamSpeakBuildLogFile.txt");
print LOGFILE "Perl script started\n";
close (LOGFILE);
open(LOGFILE, ">>TeamSpeakBuildLogFile.txt");
print LOGFILE "Perl version:".`perl --version`."\n";
close (LOGFILE);
open(LOGFILE, ">>TeamSpeakBuildLogFile.txt");
print LOGFILE "Python version:".`python --version 2>&1`."\n";
close (LOGFILE);

$installPath = $ARGV[0];
open(LOGFILE, ">>TeamSpeakBuildLogFile.txt");
print LOGFILE "InstallPath: ".$installPath."\n";
close (LOGFILE);

$currDir = `pwd`;
open(LOGFILE, ">>TeamSpeakBuildLogFile.txt");
print LOGFILE "CurrDir: ".$currDir."\n";
close (LOGFILE);

chomp $currDir; 
open(LOGFILE, ">>TeamSpeakBuildLogFile.txt");
print LOGFILE "Chomped: ".$currDir."\n";
close (LOGFILE);

$iPhonePath = `xcodebuild -version -sdk | grep ^Path | grep iPhoneOS | tail -n 1 | cut -c 7-`;
chomp $iPhonePath;
open(LOGFILE, ">>TeamSpeakBuildLogFile.txt");
print LOGFILE "Opening python script:\n";
print LOGFILE "python2.6 \'$currDir/Assets/TeamSpeak/iOS/PostBuild/TeamSpeakRunner.py\' \'$installPath\' \'$currDir/Assets/TeamSpeak/iOS\' \'$iPhonePath\'\n";
close (LOGFILE);
# TeamSpeakRunner.py will add the necessary libraries to the xcode project
`python2.6 \'$currDir/Assets/TeamSpeak/iOS/PostBuild/TeamSpeakRunner.py\' \'$installPath\' \'$currDir/Assets/TeamSpeak/iOS\' \'$iPhonePath\' \'$ARGV[1]\' `;

open(LOGFILE, ">>TeamSpeakBuildLogFile.txt");
print LOGFILE "python script done\n";
close (LOGFILE);